#!/bin/sh

# 创建主目录
if [ ! -d "${JIRA_HOME}" ]; then
  gosu "${USERNAME}" mkdir "${JIRA_HOME}"

  # 创建工作目录
  gosu "${USERNAME}" mkdir "${JIRA_HOME}/work"
fi


# 判断是否是安全连接
if [ "${PROXY_SCHEME}" = "https" ] || [ "${PROXY_SCHEME}" = "HTTPS" ] || [ "${PROXY_SCHEME}" = "Https" ]; then
  export secure="true"
else
  export secure="false"
fi

# 注入反代参数以及日志主目录
CATALINA_OPTS="${CATALINA_OPTS} -Dproxy.name=${PROXY_DOMAIN}"
CATALINA_OPTS="${CATALINA_OPTS} -Dproxy.port=${PROXY_PORT}"
CATALINA_OPTS="${CATALINA_OPTS} -Dproxy.secure=${secure}"
CATALINA_OPTS="${CATALINA_OPTS} -Dproxy.scheme=${PROXY_SCHEME}"
CATALINA_OPTS="${CATALINA_OPTS} -Dcontext.path=${CONTEXT_PATH}"
CATALINA_OPTS="${CATALINA_OPTS} -Djira.home=${JIRA_HOME}"



# 将主目录所有者改成系统创建的用户
permissionFile=${JIRA_HOME}/.permission.lock
if [ "${SET_PERMISSIONS}" = true ] && [ ! -f "${permissionFile}" ]; then
  chown -R "${USERNAME}":"${USERNAME}" "${JIRA_HOME}"
  chmod -R u=rwx,go-rwx "${JIRA_HOME}"

  chown -R "${USERNAME}":"${USERNAME}" "${CATALINA_BASE}"

  if [ ! -f "${permissionFile}" ]; then
    gosu "${USERNAME}" touch "${permissionFile}"
  fi
fi
