#!/bin/sh

# 判断是否是安全连接
if [ "${PROXY_SCHEME}" == "https" ] || [ "${PROXY_SCHEME}" == "HTTPS" ] || [ "${PROXY_SCHEME}" == "Https" ]; then
  export secure="true"
else
  export secure="false"
fi

CATALINA_OPTS="${CATALINA_OPTS} -Dproxy.name=${PROXY_DOMAIN} -Dproxy.port=${PROXY_PORT} -Dproxy.secure=${secure} -Dproxy.scheme=${PROXY_SCHEME} -Dcontext.path=${CONTEXT_PATH}"



# 将主目录所有者改成系统创建的用户
permissionFile=${JIRA_HOME}/.permission.lock
if [ "${SET_PERMISSIONS}" == true ] && [ ! -f "${permissionFile}" ]; then
  chown -R "${USERNAME}":"${USERNAME}" "${JIRA_HOME}"
  chmod -R u=rwx,go-rwx "${JIRA_HOME}"

  if [ ! -f "${permissionFile}" ]; then
    gosu "${USERNAME}" touch "${permissionFile}"
  fi
fi
